"use strict";
exports.__esModule = true;
var express_1 = require("express");
var requireAuth_1 = require("./../middleware/requireAuth");
var userControllers_1 = require("../controllers/userControllers");
var router = express_1["default"].Router();
router.post('/register', userControllers_1.register);
router.post('/login', userControllers_1.login);
router.get('/getUserInfo', requireAuth_1.requireAuth, userControllers_1.getUserInfo);
router.post('/addThread', requireAuth_1.requireAuth, userControllers_1.addThread);
router.post('/addAnswer', requireAuth_1.requireAuth, userControllers_1.addAnswer);
router.post('/addComment', requireAuth_1.requireAuth, userControllers_1.addComment);
router.put('/likeAnswer', requireAuth_1.requireAuth, userControllers_1.likeAnswer);
router.put('/dislikeAnswer', requireAuth_1.requireAuth, userControllers_1.dislikeAnswer);
router.put('/likeComment', requireAuth_1.requireAuth, userControllers_1.likeComment);
router.put('/dislikeComment', requireAuth_1.requireAuth, userControllers_1.dislikeComment);
router.put('/updateUserCredentials', requireAuth_1.requireAuth, userControllers_1.updateUserCredentials);
router.put('/disableNotification', requireAuth_1.requireAuth, userControllers_1.disableNotify);
exports["default"] = router;
